# Generated by Django 5.2.3 on 2025-06-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='votante',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=10)),
                ('papellido', models.CharField(max_length=50)),
                ('sapellido', models.CharField(max_length=50)),
                ('pnombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(max_length=50)),
                ('cv', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=50)),
                ('parroquia', models.CharField(max_length=50)),
                ('secres', models.CharField(max_length=50)),
                ('encargado', models.CharField(max_length=50)),
                ('voto', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
